---

- name: Copy K3s service file
  template:
    src: "k3s.service.j2"
    dest: "{{ systemd_dir }}/k3s-node.service"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: 0755

- name: Enable and check K3s service
  become: yes
  systemd:
    name: k3s-node
    daemon_reload: yes
    state: restarted
    enabled: yes
